const fastRefresh=debounce(()=>{refreshNonTable();updateSyncState()},60);
function initChart(id,opt){if(!window.echarts)return;let el=document.getElementById(id);if(!el)return;charts[id]=charts[id]||echarts.init(el,null,{renderer:'canvas'});charts[id].setOption(opt,true)}
function lineOption(p){return{animationDuration:700,tooltip:{trigger:'axis',valueFormatter:v=>W(v)},legend:{top:4},grid:{left:58,right:20,top:48,bottom:45},xAxis:{type:'category',data:p.map(x=>x.ym),axisLabel:{interval:Math.max(0,Math.floor(p.length/8)-1)}},yAxis:{type:'value',axisLabel:{formatter:v=>(v/1e6).toFixed(1)+'M'}},series:[{name:'현금',type:'line',smooth:.35,showSymbol:false,areaStyle:{opacity:.06},data:p.map(x=>x.cash)},{name:'투자',type:'line',smooth:.35,showSymbol:false,data:p.map(x=>x.invest)},{name:'순자산',type:'line',smooth:.35,showSymbol:false,lineStyle:{width:3},data:p.map(x=>x.net)},{name:'학자금',type:'line',smooth:.35,showSymbol:false,data:p.map(x=>x.loan)}]}}
function donutOption(data){return{animationDuration:650,tooltip:{trigger:'item',formatter:'{b}<br>{c}%'},series:[{type:'pie',radius:['52%','76%'],center:['50%','50%'],padAngle:2,itemStyle:{borderRadius:7},label:{show:false},data}]}}
function barHtml(obj,max=100){return`<div class="barlist">${Object.entries(obj).map(([k,v],i)=>`<div class="barrow"><span>${esc(k)}</span><div class="track"><div class="fill" style="width:${Math.min(100,v/max*100)}%;background:${COLORS[i%COLORS.length]}"></div></div><b>${typeof v==='number'&&max===100?PCT(v):W(v)}</b></div>`).join('')}</div>`}
function renderHero(){let p=project(),z=p.at(-1),normal=calc(Math.max(0,idx('2026-12')));heroSide.innerHTML=[['정상월 잉여',W(normal.free)],['비상금 도달',hit(S.settings.emergency)],['첫차 게이트',hit(S.settings.car)],['5년 순자산',W(z?.net||0)]].map(x=>`<div class="mini"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function renderKpis(){let p=project(),z=p.at(-1),n=calc(Math.max(0,idx(routeMonth.value||S.settings.start)));let data=[['월 수입',W(n.inc)],['월 생활·부채',W(n.liv)],['월 투자',W(n.inv)],['월 잉여',W(n.free)],['투자 기대수익률',PCT(S.settings.returnRate)],['5년 순자산',W(z?.net||0)]];kpis.innerHTML=data.map((x,i)=>`<div class="kpi"><small>${x[0]}</small><b class="${i===3?(n.free>=0?'pos':'neg'):''}">${x[1]}</b></div>`).join('')}
function renderOverview(){let p=project();initChart('netChart',lineOption(p));initChart('overviewDonut',donutOption(Object.entries(S.settings.market).map(([k,v])=>({name:MARKETS[k],value:v}))));styleBars.innerHTML=barHtml(Object.fromEntries(Object.entries(S.settings.style).map(([k,v])=>[STYLES[k],v])));let t=[...S.themes].sort((a,b)=>b.score-a.score).slice(0,5);themePulse.innerHTML=barHtml(Object.fromEntries(t.map(x=>[x.name,x.score])),10);renderCapitalFlow()}
function renderCapitalFlow(){let i=Math.max(0,idx(routeMonth.value||S.settings.start)),c=calc(i),inv=c.inv;let rows=Object.entries(S.settings.market).map(([k,v])=>[MARKETS[k],inv*v/100]);capitalFlow.innerHTML=`<div class="barlist">${rows.map((r,i)=>`<div class="barrow"><span>${r[0]}</span><div class="track"><div class="fill" style="width:${S.settings.market[Object.keys(S.settings.market)[i]]}%;background:${COLORS[i]}"></div></div><b>${W(r[1])}</b></div>`).join('')}</div><div class="sub" style="margin-top:12px">투자 예정금 ${W(inv)} 기준 · 레짐 ${S.settings.regime}</div>`}
function renderCashflow(){let p=project();let data=p.map(x=>({ym:x.ym,수입:x.inc,생활부채:x.liv,투자:x.inv,잉여:x.free}));initChart('cashChart',{animationDuration:700,tooltip:{trigger:'axis'},legend:{top:4},grid:{left:58,right:20,top:48,bottom:45},xAxis:{type:'category',data:data.map(x=>x.ym),axisLabel:{interval:Math.max(0,Math.floor(data.length/8)-1)}},yAxis:{type:'value',axisLabel:{formatter:v=>(v/1e6).toFixed(1)+'M'}},series:['수입','생활부채','투자','잉여'].map((k,i)=>({name:k,type:i===3?'line':'bar',stack:i<2?undefined:undefined,smooth:true,data:data.map(x=>x[k])}))});let z=p.at(-1);cashKpis.innerHTML=[['기간 수입',W(p.reduce((a,x)=>a+x.inc,0))],['기간 생활·부채',W(p.reduce((a,x)=>a+x.liv,0))],['기간 투자원금',W(p.reduce((a,x)=>a+x.inv,0))],['종료 현금',W(z?.cash||0)],['종료 투자',W(z?.invest||0)],['종료 부채',W(z?.loan||0)]].map(x=>`<div class="kpi"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');renderMonthDetail();renderYear()}
function renderMonthDetail(){let i=idx(cashMonth.value||S.settings.start);if(i<0||i>=S.settings.months){monthDetail.innerHTML='계획기간 밖입니다.';return}let c=calc(i),entries=Object.entries(c.p).filter(([k])=>k!=='수입').sort((a,b)=>b[1]-a[1]);monthDetail.innerHTML=`<div class="kpi" style="margin-bottom:12px"><small>잉여현금</small><b class="${c.free>=0?'pos':'neg'}">${W(c.free)}</b></div>${barHtml(Object.fromEntries(entries),Math.max(1,...entries.map(x=>x[1])))}`}
function renderYear(){let y=+cashYear.value,arr=[];for(let m=1;m<=12;m++){let i=idx(y+'-'+String(m).padStart(2,'0'));arr.push(i>=0&&i<S.settings.months?calc(i):{p:{},inc:0,liv:0,inv:0,free:0})}let cat={};arr.forEach(x=>Object.entries(x.p).forEach(([k,v])=>{if(k!=='수입')cat[k]=(cat[k]||0)+v}));initChart('yearCategory',{animationDuration:650,tooltip:{trigger:'item',valueFormatter:v=>W(v)},grid:{left:100,right:20,top:15,bottom:35},xAxis:{type:'value',axisLabel:{formatter:v=>(v/1e6).toFixed(1)+'M'}},yAxis:{type:'category',data:Object.keys(cat)},series:[{type:'bar',data:Object.values(cat),itemStyle:{borderRadius:[0,6,6,0]}}]});let t=arr.reduce((z,x)=>({inc:z.inc+x.inc,liv:z.liv+x.liv,inv:z.inv+x.inv,free:z.free+x.free}),{inc:0,liv:0,inv:0,free:0});yearSummary.innerHTML=`<div class="grid3"><div class="mini"><small>수입</small><b>${W(t.inc)}</b></div><div class="mini"><small>생활·부채</small><b>${W(t.liv)}</b></div><div class="mini"><small>투자</small><b>${W(t.inv)}</b></div></div><div class="callout" style="margin-top:12px"><b>연간 잉여</b>${W(t.free)}</div>`}
function sortedItems(){let q=itemSearch.value.trim().toLowerCase(),p=partFilter.value,pr=priorityFilter.value;return S.items.filter(x=>(!p||x.part===p)&&(!pr||String(x.priority)===pr)&&(!q||(x.name+x.sub+x.part).toLowerCase().includes(q))).sort((a,b)=>(a.priority-b.priority)||PARTS.indexOf(a.part)-PARTS.indexOf(b.part)||a.name.localeCompare(b.name,'ko'))}
function priorityBadge(n){return`<span class="priority-badge rank${n}"><i></i>${n} ${PRIORITY_LABEL[n]}</span>`}
function renderItems(){itemRows.innerHTML=sortedItems().map(x=>`<tr data-id="${x.id}" class="${x.active?'':'off'}"><td><input data-k="active" type="checkbox" ${x.active?'checked':''}></td><td><select class="edit" data-k="priority">${[1,2,3,4,5].map(n=>`<option value="${n}" ${n==x.priority?'selected':''}>${n} ${PRIORITY_LABEL[n]}</option>`)}</select></td><td><select class="edit" data-k="part">${PARTS.map(z=>`<option ${z===x.part?'selected':''}>${z}</option>`)}</select></td><td><input class="edit" data-k="sub" value="${esc(x.sub)}"></td><td><input class="edit" data-k="name" value="${esc(x.name)}"></td><td><select class="edit" data-k="type">${['필수','선택','목표','수입'].map(z=>`<option ${z===x.type?'selected':''}>${z}</option>`)}</select></td><td><select class="edit" data-k="freq">${['월','일','주','연','일회성'].map(z=>`<option ${z===x.freq?'selected':''}>${z}</option>`)}</select></td><td><input class="edit" data-k="amount" type="number" value="${x.amount}"></td><td><input class="edit" data-k="qty" type="number" step=".1" value="${x.qty}"></td><td>${x.freq==='일회성'?'-':W(mv(x))}</td><td><input class="edit" data-k="start" type="month" value="${x.start}"></td><td><input class="edit" data-k="end" type="month" value="${x.end||''}"></td><td><button class="soft danger del">삭제</button></td></tr>`).join('')}
function updateItemFromInput(e){let tr=e.target.closest('tr');if(!tr)return;let x=S.items.find(y=>y.id===tr.dataset.id),k=e.target.dataset.k;if(!x||!k)return;let v=e.target.type==='checkbox'?e.target.checked:e.target.value;if(['amount','qty','priority'].includes(k))v=+v||0;x[k]=v;S.updated=Date.now();localStorage.setItem(KEY,JSON.stringify(S));if(['priority','part','type','freq','start','end','active'].includes(k)){renderItems()}fastRefresh()}
function renderMarketInputs(){let total=sum(S.settings.market);marketInputs.innerHTML=Object.entries(S.settings.market).map(([k,v],i)=>`<div class="alloc-row"><span><i class="swatch" style="background:${COLORS[i]}"></i>${MARKETS[k]}</span><input type="number" step="1" data-market="${k}" value="${v}"><b>${PCT(v)}</b></div>`).join('');marketWarning.textContent=`합계 ${PCT(total)} ${Math.abs(total-100)<.01?'· 정상':'· 100%로 맞추는 것이 좋습니다.'}`;initChart('marketDonut',donutOption(Object.entries(S.settings.market).map(([k,v])=>({name:MARKETS[k],value:v}))))}
function renderStyleInputs(){let total=sum(S.settings.style);styleInputs.innerHTML=Object.entries(S.settings.style).map(([k,v],i)=>`<div class="alloc-row"><span><i class="swatch" style="background:${COLORS[i+5]}"></i>${STYLES[k]}</span><input type="number" step="1" data-style="${k}" value="${v}"><b>${PCT(v)}</b></div>`).join('');styleWarning.textContent=`합계 ${PCT(total)} ${Math.abs(total-100)<.01?'· 정상':'· 100%로 맞추는 것이 좋습니다.'}`}
function renderMatrix(){let ms=Object.entries(S.settings.market),ss=Object.entries(S.settings.style),vals=[];ms.forEach(([m,mv])=>ss.forEach(([s,sv])=>vals.push(mv*sv/100)));let mx=Math.max(...vals,1),html=`<div class="matrix"><div></div>${ss.map(([s])=>`<div class="head">${STYLES[s]}</div>`).join('')}`;ms.forEach(([m,mv])=>{html+=`<div class="head">${MARKETS[m]}</div>`;ss.forEach(([s,sv])=>{let v=mv*sv/100,a=.08+.38*v/mx;html+=`<div class="heat" style="background:rgba(0,113,227,${a})"><b>${PCT(v)}</b></div>`})});allocationMatrix.innerHTML=html+'</div>'}
function renderHoldings(){holdingRows.innerHTML=S.holdings.map(h=>`<tr data-id="${h.id}"><td>${MARKETS[h.market]}</td><td>${esc(h.name)}</td><td>${esc(h.ticker)}</td><td>${STYLES[h.style]}</td><td>${esc(h.theme)}</td><td><input class="edit hv" type="number" value="${h.value}"></td><td><button class="soft danger hdel">삭제</button></td></tr>`).join('');let totals={us:0,kr:0,crypto:0,cash:0,gold:0};S.holdings.forEach(h=>totals[h.market]=(totals[h.market]||0)+(+h.value||0));let all=sum(totals),diff={};Object.keys(totals).forEach(k=>diff[MARKETS[k]]=all?totals[k]/all*100-S.settings.market[k]:-S.settings.market[k]);actualVsTarget.innerHTML=`<b>실제-목표 비중 차이</b><div style="margin-top:10px">${barHtml(Object.fromEntries(Object.entries(diff).map(([k,v])=>[k,Math.abs(v)])),Math.max(1,...Object.values(diff).map(Math.abs)))}</div><div class="sub" style="margin-top:10px">+는 목표보다 과대, -는 과소. 상세 부호는 ${Object.entries(diff).map(([k,v])=>`${k} ${v>=0?'+':''}${v.toFixed(1)}%p`).join(' · ')}</div>`}
function renderPortfolio(){renderMarketInputs();renderStyleInputs();renderMatrix();renderHoldings()}
function renderStrategy(){strategyFlow.innerHTML=`<div class="flow-col"><div class="flow-node"><b>Strategic Core</b><br><span class="sub">시장 beta · 장기 · 분산</span></div><div class="flow-node"><b>방어자산</b><br><span class="sub">현금·채권·금</span></div></div><div class="arrow">→</div><div class="flow-col"><div class="flow-node"><b>Satellite</b><br><span class="sub">테마·스윙·한국/미국 선택</span></div><div class="flow-node"><b>Crypto</b><br><span class="sub">별도 상한과 손실예산</span></div></div><div class="arrow">→</div><div class="flow-col"><div class="flow-node"><b>System</b><br><span class="sub">신호·사이징·리스크게이트</span></div><div class="flow-node"><b>Review</b><br><span class="sub">벤치마크·MDD·OOS</span></div></div>`;let r=S.settings.risk;riskRules.innerHTML=[['개별 종목 최대비중',PCT(r.maxPosition),r.maxPosition<=10],['단일 테마 최대비중',PCT(r.maxTheme),r.maxTheme<=25],['일 손실 한도',PCT(r.maxDailyLoss),r.maxDailyLoss<=2],['월 손실 한도',PCT(r.maxMonthlyLoss),r.maxMonthlyLoss<=8],['시스템 자본 상한',PCT(r.systemCapital),r.systemCapital<=20],['코인 총비중 상한',PCT(r.cryptoCap),r.cryptoCap<=15]].map(x=>`<div class="rule"><div><b>${x[0]}</b><div class="sub">현재 ${x[1]}</div></div><span class="status ${x[2]?'':'warn'}">${x[2]?'보수적':'재검토'}</span></div>`).join('');riskForm.innerHTML=[['maxPosition','개별 종목 최대 %'],['maxTheme','단일 테마 최대 %'],['maxDailyLoss','일 손실 한도 %'],['maxMonthlyLoss','월 손실 한도 %'],['systemCapital','시스템 자본 상한 %'],['cryptoCap','코인 총비중 상한 %']].map(([k,l])=>`<label class="field">${l}<input type="number" step=".1" data-risk="${k}" value="${r[k]}"></label>`).join('')}
function renderThemes(){initChart('themeRadar',{animationDuration:700,tooltip:{},radar:{indicator:S.themes.slice(0,8).map(x=>({name:x.name.split('·')[0],max:10})),radius:'67%'},series:[{type:'radar',areaStyle:{opacity:.12},data:[{value:S.themes.slice(0,8).map(x=>x.score),name:'테마 점수'}]}]});themeCards.innerHTML=[...S.themes].sort((a,b)=>b.score-a.score).map((t,i)=>`<article class="theme" style="--c:${COLORS[i%COLORS.length]}"><div class="meta">${esc(t.markets)}</div><div class="score">${t.score}<span class="sub">/10</span></div><b>${esc(t.name)}</b><div class="meta" style="margin-top:6px">${esc(t.note)}</div><div class="chips">${t.groups.map(g=>`<span class="chip">${esc(g)}</span>`).join('')}</div><div class="scoreline" data-theme="${t.id}">${[5,6,7,8,9,10].map(n=>`<button class="${n===t.score?'on':''}" data-score="${n}">${n}</button>`).join('')}</div></article>`).join('')}
function renderGoals(){let p=project(),z=p.at(-1),goals=[['비상금',S.settings.emergency,z?.cash||0],['첫차',S.settings.car,z?.cash||0],['학자금 상환',S.settings.loan,S.settings.loan-(z?.loan||0)],['투자 3천만원',30000000,z?.invest||0]];goalList.innerHTML=goals.map(g=>{let pc=Math.max(0,Math.min(100,g[2]/Math.max(1,g[1])*100));return`<div class="goal"><div class="goal-head"><b>${g[0]}</b><span>${PCT(pc)}</span></div><div class="track"><div class="fill" style="width:${pc}%;background:${COLORS[goals.indexOf(g)]}"></div></div><div class="sub">${W(g[2])} / ${W(g[1])}</div></div>`}).join('');let fields=[['cash','현재 현금'],['invest','현재 투자자산'],['loan','학자금 잔액'],['loanRate','학자금 금리 %'],['emergency','비상금 목표'],['car','차량 현금 게이트'],['returnRate','투자 기대수익률 %'],['months','계획 개월']];goalForm.innerHTML=fields.map(([k,l])=>`<label class="field">${l}<input type="number" step=".1" data-setting="${k}" value="${S.settings[k]}"></label>`).join('')}
function updateSyncState(){let pending=S.updated>(S.lastNotionExported||0);let n=S.items.length+S.holdings.length+S.themes.length;syncState.innerHTML=`<b>${pending?'Notion 반영 대기 변경 있음':'마지막 반영 패키지 생성 후 추가 변경 없음'}</b><br><span class="sub">웹 저장 ${new Date(S.updated).toLocaleString('ko-KR')} · 관리 객체 ${n}개${S.lastNotionExported?` · 마지막 반영 패키지 ${new Date(S.lastNotionExported).toLocaleString('ko-KR')}`:''}</span>`;storageInfo.innerHTML=`브라우저 키 <code>${KEY}</code><br>항목 ${S.items.length}개 · 보유자산 ${S.holdings.length}개 · 테마 ${S.themes.length}개<br>마지막 저장 ${new Date(S.updated).toLocaleString('ko-KR')}`}
function renderAll(){renderHero();renderKpis();renderOverview();renderCashflow();renderItems();renderPortfolio();renderStrategy();renderThemes();renderGoals();updateSyncState();observeReveal()}
function refreshNonTable(){renderHero();renderKpis();renderOverview();renderCashflow();renderPortfolio();renderStrategy();renderThemes();renderGoals()}
function normalize(obj){let t=sum(obj);if(!t)return;Object.keys(obj).forEach(k=>obj[k]=Math.round(obj[k]/t*1000)/10);let diff=100-sum(obj),first=Object.keys(obj)[0];obj[first]=Math.round((obj[first]+diff)*10)/10}
function applyRegime(r){let presets={riskoff:{us:35,kr:15,crypto:5,cash:35,gold:10},neutral:{us:45,kr:25,crypto:10,cash:15,gold:5},riskon:{us:50,kr:25,crypto:15,cash:5,gold:5}};S.settings.regime=r;S.settings.market={...presets[r]};saveState();renderPortfolio();document.querySelectorAll('#regimeSeg button').forEach(b=>b.classList.toggle('on',b.dataset.r===r))}
function dl(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function notionPayload(){return{version:10,generatedAt:new Date().toISOString(),mode:'batch_apply',items:S.items,holdings:S.holdings,themes:S.themes,settings:S.settings,webUpdated:S.updated,notionDashboard:'https://app.notion.com/p/3d4d710e405a81ba86e5f0689e2ff475?pvs=204'}}
function observeReveal(){let els=document.querySelectorAll('.motion-reveal:not(.seen)');if(!('IntersectionObserver'in window)){els.forEach(x=>x.classList.add('seen'));return}let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');io.unobserve(e.target)}}),{threshold:.08});els.forEach(x=>io.observe(x))}
function resizeCharts(){Object.values(charts).forEach(c=>c&&c.resize())}
